-- tblSites
COMMENT ON TABLE dima."tblSites" IS 'Contains site level data (user defined plot groupings).';
COMMENT ON COLUMN dima."tblSites"."SiteKey" IS 'Unique key for Site';
COMMENT ON COLUMN dima."tblSites"."DateModified" IS 'Date site record was last modified';
COMMENT ON COLUMN dima."tblSites"."SiteID" IS 'Site ID provided by user';
COMMENT ON COLUMN dima."tblSites"."SiteName" IS 'Name of site provided by user';
COMMENT ON COLUMN dima."tblSites"."Ownership" IS 'Primary ownership of the site';
COMMENT ON COLUMN dima."tblSites"."ContactName" IS 'Person to contact about the site';
COMMENT ON COLUMN dima."tblSites"."MgtObject" IS 'Stated management objective(s) for the site';
COMMENT ON COLUMN dima."tblSites"."MonObject" IS 'Stated monitoring objective(s) for the site';
COMMENT ON COLUMN dima."tblSites"."Notes" IS 'Notes related to site';
COMMENT ON COLUMN dima."tblSites"."uploaded" IS 'Has the site definition been uploaded to a SQL Server DIMA instance?';

-- tblPlots
COMMENT ON TABLE dima."tblPlots" IS 'Contains data specific to the plot or plot establishment protocol(s).';
COMMENT ON COLUMN dima."tblPlots"."SiteKey" IS 'Unique key for Site';
COMMENT ON COLUMN dima."tblPlots"."PlotKey" IS 'Unique key for Plot';
COMMENT ON COLUMN dima."tblPlots"."DateModified" IS 'Date information was modified for this site/plot';
COMMENT ON COLUMN dima."tblPlots"."PlotID" IS 'Plot Identification';
COMMENT ON COLUMN dima."tblPlots"."genericPlot" IS 'Indicates plot is generic and not associated with a predefined site and plot';
COMMENT ON COLUMN dima."tblPlots"."EstablishDate" IS 'Date plot was originally established (defaults to today''s date although user can modify)';
COMMENT ON COLUMN dima."tblPlots"."State" IS 'State where plot is located';
COMMENT ON COLUMN dima."tblPlots"."County" IS 'County where plot is located';
COMMENT ON COLUMN dima."tblPlots"."Directions" IS 'Directions to plot';
COMMENT ON COLUMN dima."tblPlots"."AvgPrecip" IS 'Average precipitation';
COMMENT ON COLUMN dima."tblPlots"."AvgPrecipUOM" IS 'Units of measure for average precipitation';
COMMENT ON COLUMN dima."tblPlots"."EcolSite" IS 'Ecological Site for plot';
COMMENT ON COLUMN dima."tblPlots"."EcolSiteMLRA" IS 'NOT CURRENTLY USED';
COMMENT ON COLUMN dima."tblPlots"."EcolSiteSubMLRA" IS 'NOT CURRENTLY USED';
COMMENT ON COLUMN dima."tblPlots"."EcolSiteNum" IS 'NOT CURRENTLY USED';
COMMENT ON COLUMN dima."tblPlots"."EcolSiteState" IS 'State for ecological site';
COMMENT ON COLUMN dima."tblPlots"."Soil" IS 'Map unit symbol';
COMMENT ON COLUMN dima."tblPlots"."ParentMaterial" IS 'See Parent Material tab';
COMMENT ON COLUMN dima."tblPlots"."Slope" IS 'Slope in percent';
COMMENT ON COLUMN dima."tblPlots"."Aspect" IS 'Aspect in degrees';
COMMENT ON COLUMN dima."tblPlots"."ESD_SlopeShape" IS '"Linear linear, linear concave, linear convex, concave linear, concave concave, concave convex, convex linear, convex concave, convex convex"';
COMMENT ON COLUMN dima."tblPlots"."LandscapeType" IS '"hills/mountains, fan piedmont, flood plain/flood basin, terrace, flat plain, dunes, other"';
COMMENT ON COLUMN dima."tblPlots"."LandscapeTypeSecondary" IS 'if landscape = terrace then "riser, tread, other"; if landscape = hills/mountains then "summit, shoulder, backslope, footslope, toeslope, other"; if anything else then "Other"';
COMMENT ON COLUMN dima."tblPlots"."MgtUnit" IS '"allotment or pasture"';
COMMENT ON COLUMN dima."tblPlots"."GPSCoordSys" IS 'GPS coordinate system used';
COMMENT ON COLUMN dima."tblPlots"."Datum" IS 'GPS datum of plot';
COMMENT ON COLUMN dima."tblPlots"."Zone" IS 'GPS zone of plot';
COMMENT ON COLUMN dima."tblPlots"."Easting" IS 'GPS easting of plot';
COMMENT ON COLUMN dima."tblPlots"."Northing" IS 'GPS northing of plot';
COMMENT ON COLUMN dima."tblPlots"."Elevation" IS 'Elevation of plot';
COMMENT ON COLUMN dima."tblPlots"."ElevationType" IS '"meters (1) or ft (2)"';
COMMENT ON COLUMN dima."tblPlots"."RecentWeatherPast12" IS 'Recent weather in the past 12 months';
COMMENT ON COLUMN dima."tblPlots"."RecentWeatherPrevious12" IS 'Recent weather in the 12 months prior to the last year';
COMMENT ON COLUMN dima."tblPlots"."DisturbWildfire" IS 'Wildfire disturbance (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbRodents" IS 'Rodent disturbance (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbMammals" IS 'Mammal disturbance (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbWater" IS 'Water disturbance (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbWind" IS 'Wind Disturbance (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbWaterSoilDep" IS 'Soil Deposition from Water (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbWindSoilDep" IS 'Soil Deposition from Wind (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbUndgroundUtils" IS 'Underground Utilities (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbOverhdTransLines" IS 'Overhead Transmission Lines (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbOther" IS 'Other Disturbance (yes/no)';
COMMENT ON COLUMN dima."tblPlots"."DisturbOtherDesc" IS 'Description of Other disturbance';
COMMENT ON COLUMN dima."tblPlots"."WildlifeUse" IS 'Description of wildlife use';
COMMENT ON COLUMN dima."tblPlots"."MgtHistory" IS 'Description of management history';
COMMENT ON COLUMN dima."tblPlots"."OffsiteInfluences" IS 'Description of offsite influences';
COMMENT ON COLUMN dima."tblPlots"."Comments" IS 'Other comments';
COMMENT ON COLUMN dima."tblPlots"."SpeciesList" IS 'Plot Species List (species separated by semi-colons)';
COMMENT ON COLUMN dima."tblPlots"."DensityList" IS 'Density Species List (species separated by semi-colons) for Plant Density method';
COMMENT ON COLUMN dima."tblPlots"."ESD_MLRA" IS 'MLRA for plot';
COMMENT ON COLUMN dima."tblPlots"."ESD_CRA" IS 'LRU/CRA for plot';
COMMENT ON COLUMN dima."tblPlots"."ESD_Region" IS 'Region';
COMMENT ON COLUMN dima."tblPlots"."ESD_Investigators" IS 'Names of investigators collecting ESD data';
COMMENT ON COLUMN dima."tblPlots"."ESD_Bedrock" IS 'See Bedrock tab';
COMMENT ON COLUMN dima."tblPlots"."ESD_MajorLandform" IS 'See Landforms tab';
COMMENT ON COLUMN dima."tblPlots"."ESD_ComponentLandform" IS 'user description of landform';
COMMENT ON COLUMN dima."tblPlots"."HillslopeType" IS '"Lower, Middle, Upper, Footslope, Backslope, Toeslope, Shoulder, Summit, Crest, NA"';
COMMENT ON COLUMN dima."tblPlots"."ESD_GeomorphicComp" IS 'See Geomorphic tab';
COMMENT ON COLUMN dima."tblPlots"."ESD_RunIn_RunOff" IS 'Type of run off:  "in, off or netural"';
COMMENT ON COLUMN dima."tblPlots"."ESD_SlopeComplexity" IS '"complex or simple"';
COMMENT ON COLUMN dima."tblPlots"."ESD_LitterClass" IS 'Litter Class ("none = none, + = few, 1 = <0.1%, 2 = 0.1-1%, 3 = 1-5%, 4 = 5-10%, 5 = 10-25%, 6 = 25-33%, 7 = 33-50%, 8 = 50-75%, 9 = >75%")';
COMMENT ON COLUMN dima."tblPlots"."ESD_Series" IS 'ESD Soil Series';
COMMENT ON COLUMN dima."tblPlots"."ESD_ParticleSizeClass" IS '"Ashy, Ashy-pumiceous, Ashy-skeletal, Cindery, Clayey, Clayey-skeletal, Coarse-loamy, Coarse-silty, Fine, Fine-loamy, Fine-silty, Fragmental, Hydrous, Hydrous-pumiceous, Hydrous-skeletal, Loamy, Loamy-skeletal, Medial, Medial-pumiceous, Medial-skeletal, P';
COMMENT ON COLUMN dima."tblPlots"."ESD_Mineralogy" IS '"Allitic, Amorphic, Carbonatic, Ferrihydritic, Ferritic, Ferruginous, Gibbsitic, Glauconitic, Gypsic, Halloysitic, Illitic, Isotic, Kaolinitic, Magnesic, Micaceous, Mixed, Paramicaceous, Parasesquic, Sesquic, Siliceous, Smectitic, Vermiculitic"';
COMMENT ON COLUMN dima."tblPlots"."ESD_SoilTempRegime" IS '"Cryic, Frigid, Hypergelic, Hyperthermic, Isofrigid, Isohyperthermic, Isomesic, Isothermic, Mesic, Pergelic ,Subgelic, Thermic"';
COMMENT ON COLUMN dima."tblPlots"."ESD_DepthClass" IS '"shallow or nonshallow"';
COMMENT ON COLUMN dima."tblPlots"."ESD_Subgroup" IS 'Subgroup';
COMMENT ON COLUMN dima."tblPlots"."ESD_Greatgroup" IS 'Greatgroup';
COMMENT ON COLUMN dima."tblPlots"."ESD_Reaction" IS 'Reaction';
COMMENT ON COLUMN dima."tblPlots"."ESD_SoilMoistureRegime" IS '"Aquic; Aridic; Torric; Udic; Ustic; Xeric"';
COMMENT ON COLUMN dima."tblPlots"."ESD_CationExchangeActivityClass" IS 'Cation exchange activity class';
COMMENT ON COLUMN dima."tblPlots"."ESD_Epipedon" IS 'User defined Epipedon';
COMMENT ON COLUMN dima."tblPlots"."ESD_Subsurface_features" IS 'User defined notes on subsurface features';
COMMENT ON COLUMN dima."tblPlots"."ESD_Depth_to_root_horizon" IS 'Depth to root restrictive horizon in cm';
COMMENT ON COLUMN dima."tblPlots"."ESD_Type_root_horizon" IS 'Type of root restrictive horizon';
COMMENT ON COLUMN dima."tblPlots"."ESD_Horizon_notes" IS 'User defined notes on horizons';
COMMENT ON COLUMN dima."tblPlots"."ESD_TrackingID" IS 'User defined tracking number for ESC';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Assoc1" IS 'Associated Ecological Site';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Assoc2" IS 'Associated Ecological Site';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Assoc3" IS 'Associated Ecological Site';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Similar1" IS 'Similar Ecological Site';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Similar2" IS 'Similar Ecological Site';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Similar3" IS 'Similar Ecological Site';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Notes" IS 'User notes on the ecological site';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Lookup1" IS 'Self-defined Lookup table';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Lookup2" IS 'Self-defined Lookup table';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Lookup3" IS 'Self-defined Lookup table';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Text1" IS 'Self-defined text box';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Text2" IS 'Self-defined text box';
COMMENT ON COLUMN dima."tblPlots"."EcolSite_Text3" IS 'Self-defined text box';
COMMENT ON COLUMN dima."tblPlots"."ESD_RecentWeatherPast12" IS '"normal, drought, wet"';
COMMENT ON COLUMN dima."tblPlots"."ESD_ErosionPatternClass" IS '"0 No evidence of erosion or deposition; 1 Very slight soil redistribution; 2 Patchy, slight (<5 cm) soil loss and deposition....patterns, but low soil loss patterns, but low soil loss; 3a Extensive, moderate soil loss (<10 cm); 3b Extensive, moderate soi';
COMMENT ON COLUMN dima."tblPlots"."Longitude" IS 'GPS Longitude (convert Easting if entered)';
COMMENT ON COLUMN dima."tblPlots"."Latitude" IS 'GPS Latitude (convert Northing if entered)';
COMMENT ON COLUMN dima."tblPlots"."CoordLabel1" IS 'Label of unique landscape feature (well, etc)';
COMMENT ON COLUMN dima."tblPlots"."CoordDistance1" IS 'Distance to plot';
COMMENT ON COLUMN dima."tblPlots"."Longitude1" IS 'GPS Longitude';
COMMENT ON COLUMN dima."tblPlots"."Latitude1" IS 'GPS Latitude';
COMMENT ON COLUMN dima."tblPlots"."Easting1" IS 'GPS Easting';
COMMENT ON COLUMN dima."tblPlots"."Northing1" IS 'GPS Northing';
COMMENT ON COLUMN dima."tblPlots"."CoordLabel2" IS 'Label of unique landscape feature (well, etc)';
COMMENT ON COLUMN dima."tblPlots"."CoordDistance2" IS 'Distance to plot';
COMMENT ON COLUMN dima."tblPlots"."Longitude2" IS 'GPS Longitude';
COMMENT ON COLUMN dima."tblPlots"."Latitude2" IS 'GPS Latitude';
COMMENT ON COLUMN dima."tblPlots"."Easting2" IS 'GPS Easting';
COMMENT ON COLUMN dima."tblPlots"."Northing2" IS 'GPS Northing';
COMMENT ON COLUMN dima."tblPlots"."CoordLabel3" IS 'Label of unique landscape feature (well, etc)';
COMMENT ON COLUMN dima."tblPlots"."CoordDistance3" IS 'Distance to plot';
COMMENT ON COLUMN dima."tblPlots"."Longitude3" IS 'GPS Longitude';
COMMENT ON COLUMN dima."tblPlots"."Latitude3" IS 'GPS Latitude';
COMMENT ON COLUMN dima."tblPlots"."Easting3" IS 'GPS Easting';
COMMENT ON COLUMN dima."tblPlots"."Northing3" IS 'GPS Northing';

-- tblLines
COMMENT ON TABLE dima."tblLines" IS 'Contains data specific to the transect or transect establishment protocol(s).';
COMMENT ON COLUMN dima."tblLines"."PlotKey" IS 'Unique key for Plot';
COMMENT ON COLUMN dima."tblLines"."LineKey" IS 'Unique key for Line (transect)';
COMMENT ON COLUMN dima."tblLines"."DateModified" IS 'Date site record was last modified';
COMMENT ON COLUMN dima."tblLines"."LineID" IS 'ID number assigned to lines when they are created. Can be modified by user later on through plot form';
COMMENT ON COLUMN dima."tblLines"."Azimuth" IS 'Compass bearing of direction transect is oriented from plot center';
COMMENT ON COLUMN dima."tblLines"."ElevationType" IS 'Whether elevations are expressed in meters or feet';
COMMENT ON COLUMN dima."tblLines"."NorthType" IS 'Whether azimuth has been corrected for declination (True) or not (Magnetic)';
COMMENT ON COLUMN dima."tblLines"."NorthingStart" IS 'UTM coordinate northing value for transect start. Comment: Not used for AIM';
COMMENT ON COLUMN dima."tblLines"."EastingStart" IS 'UTM coordinate easting value for transect start. Comment: Not used for AIM';
COMMENT ON COLUMN dima."tblLines"."ElevationStart" IS 'Elevation for transect start';
COMMENT ON COLUMN dima."tblLines"."NorthingEnd" IS 'UTM coordinate northing value for transect end. Comment: Not used for AIM';
COMMENT ON COLUMN dima."tblLines"."EastingEnd" IS 'UTM coordinate easting value for transect end. Comment: Not used for AIM';
COMMENT ON COLUMN dima."tblLines"."ElevationEnd" IS 'Elevation for transect end';
COMMENT ON COLUMN dima."tblLines"."LatitudeStart" IS 'Decimal degrees latitude for transect start';
COMMENT ON COLUMN dima."tblLines"."LongitudeStart" IS 'Decimal degrees longitude for transect start';
COMMENT ON COLUMN dima."tblLines"."LatitudeEnd" IS 'Decimal degrees latitude for transect end';
COMMENT ON COLUMN dima."tblLines"."LongitudeEnd" IS 'Decimal degrees longitude for transect end';

-- tblGapHeader
COMMENT ON TABLE dima."tblGapHeader" IS 'Contains method metadata and summary data for the Gap Intercept method (Monitoring Manual v1 2nd ed., Core Methods, p. 41).';
COMMENT ON COLUMN dima."tblGapHeader"."LineKey" IS 'Unique key for line (transect)';
COMMENT ON COLUMN dima."tblGapHeader"."RecKey" IS 'Unique key for gap record';
COMMENT ON COLUMN dima."tblGapHeader"."DateModified" IS 'Date record was created or last modified';
COMMENT ON COLUMN dima."tblGapHeader"."FormType" IS 'Form for Gap data collection';
COMMENT ON COLUMN dima."tblGapHeader"."FormDate" IS 'Date data was collected (defaults to today''s date although user can modify)';
COMMENT ON COLUMN dima."tblGapHeader"."Observer" IS 'Person taking the actual measurements';
COMMENT ON COLUMN dima."tblGapHeader"."Recorder" IS 'Person doing the recording of measurements in the database or on paper forms';
COMMENT ON COLUMN dima."tblGapHeader"."DataEntry" IS 'Person doing transcription of data into the database if it was recorded on paper';
COMMENT ON COLUMN dima."tblGapHeader"."DataErrorChecking" IS 'Person doing error checking of data';
COMMENT ON COLUMN dima."tblGapHeader"."Direction" IS 'Whether the transect is read from low-to-high or high-to-low';
COMMENT ON COLUMN dima."tblGapHeader"."Measure" IS 'Data collected in metric or english units';
COMMENT ON COLUMN dima."tblGapHeader"."LineLengthAmount" IS 'Length of the gap intercept transect(line)';
COMMENT ON COLUMN dima."tblGapHeader"."GapMin" IS 'Minimum gap size in cm';
COMMENT ON COLUMN dima."tblGapHeader"."GapData" IS 'What kind of gap data are being rcorded: canopy gap, basal gap, or both';
COMMENT ON COLUMN dima."tblGapHeader"."PerennialsCanopy" IS 'Do perennial plants stop a gap? (i.e., are they considered to be "canopy")';
COMMENT ON COLUMN dima."tblGapHeader"."AnnualGrassesCanopy" IS 'Do annual grasses stop a gap?';
COMMENT ON COLUMN dima."tblGapHeader"."AnnualForbsCanopy" IS 'Do annual forbs stop a gap?';
COMMENT ON COLUMN dima."tblGapHeader"."OtherCanopy" IS 'Are there other species or elements that stop a gap? Comment: Should be listed in the notes if this is checked.';
COMMENT ON COLUMN dima."tblGapHeader"."sumCanCat1" IS 'Total length of canopy gaps in size class 1. Comment: Size classes are: 25-50cm, 50-100cm, 100-200cm, >200cm';
COMMENT ON COLUMN dima."tblGapHeader"."sumCanCat2" IS 'Total length of canopy gaps in size class 2';
COMMENT ON COLUMN dima."tblGapHeader"."sumCanCat3" IS 'Total length of canopy gaps in size class 3';
COMMENT ON COLUMN dima."tblGapHeader"."sumCanCat4" IS 'Total length of canopy gaps in size class 4';
COMMENT ON COLUMN dima."tblGapHeader"."pctCanCat1" IS 'Percent of transect in canopy gaps of size class 1';
COMMENT ON COLUMN dima."tblGapHeader"."pctCanCat2" IS 'Percent of transect in canopy gaps of size class 2';
COMMENT ON COLUMN dima."tblGapHeader"."pctCanCat3" IS 'Percent of transect in canopy gaps of size class 3';
COMMENT ON COLUMN dima."tblGapHeader"."pctCanCat4" IS 'Percent of transect in canopy gaps of size class 4';
COMMENT ON COLUMN dima."tblGapHeader"."sumBasCat1" IS 'Total length of Basal gaps in size class 1';
COMMENT ON COLUMN dima."tblGapHeader"."sumBasCat2" IS 'Total length of Basal gaps in size class 2';
COMMENT ON COLUMN dima."tblGapHeader"."sumBasCat3" IS 'Total length of Basal gaps in size class 3';
COMMENT ON COLUMN dima."tblGapHeader"."sumBasCat4" IS 'Total length of Basal gaps in size class 4';
COMMENT ON COLUMN dima."tblGapHeader"."pctBasCat1" IS 'Percent of transect in Basal gaps of size class 1';
COMMENT ON COLUMN dima."tblGapHeader"."pctBasCat2" IS 'Percent of transect in Basal gaps of size class 2';
COMMENT ON COLUMN dima."tblGapHeader"."pctBasCat3" IS 'Percent of transect in Basal gaps of size class 3';
COMMENT ON COLUMN dima."tblGapHeader"."pctBasCat4" IS 'Percent of transect in Basal gaps of size class 4';
COMMENT ON COLUMN dima."tblGapHeader"."Notes" IS 'Notes about the gap intercept data collection for the transect/line';
COMMENT ON COLUMN dima."tblGapHeader"."NoCanopyGaps" IS 'True when no canopy gaps exist for the line (transect)';
COMMENT ON COLUMN dima."tblGapHeader"."NoBasalGaps" IS 'True when no basal gaps exist for the line (transect)';

-- tblGapDetail
COMMENT ON TABLE dima."tblGapDetail" IS 'Contains data for the Gap Intercept method.';
COMMENT ON COLUMN dima."tblGapDetail"."RecKey" IS 'Unique record key for canopy gap record';
COMMENT ON COLUMN dima."tblGapDetail"."SeqNo" IS 'AutoNumber';
COMMENT ON COLUMN dima."tblGapDetail"."RecType" IS 'C=Canopy, B=Basal';
COMMENT ON COLUMN dima."tblGapDetail"."GapStart" IS 'Start position of canopy/basal gap along transect (line)';
COMMENT ON COLUMN dima."tblGapDetail"."GapEnd" IS 'End position of canopy/basal gap along transect (line)';
COMMENT ON COLUMN dima."tblGapDetail"."Gap" IS 'Length of canopy/basal gap';

-- tblLPIHeader
COMMENT ON TABLE dima."tblLPIHeader" IS 'Contains method metadata and summary data for the Line-point Intercept method (Monitoring Manual v1 2nd ed., Core Methods, p. 27).';
COMMENT ON COLUMN dima."tblLPIHeader"."LineKey" IS 'Unique key for line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."RecKey" IS 'Unique record key for line-point intercept record';
COMMENT ON COLUMN dima."tblLPIHeader"."DateModified" IS 'Date record was created or last modified';
COMMENT ON COLUMN dima."tblLPIHeader"."FormType" IS 'Form for LPI data collection';
COMMENT ON COLUMN dima."tblLPIHeader"."FormDate" IS 'Date data was collected (defaults to today''s date although user can modify)';
COMMENT ON COLUMN dima."tblLPIHeader"."Observer" IS 'Person taking the actual measurements';
COMMENT ON COLUMN dima."tblLPIHeader"."Recorder" IS 'Person doing the recording of measurements in the database or on paper forms';
COMMENT ON COLUMN dima."tblLPIHeader"."DataEntry" IS 'Person doing transcription of data into the database if it was recorded on paper';
COMMENT ON COLUMN dima."tblLPIHeader"."DataErrorChecking" IS 'Person doing error checking of data';
COMMENT ON COLUMN dima."tblLPIHeader"."Direction" IS 'Whether the transect is read from low-to-high or high-to-low';
COMMENT ON COLUMN dima."tblLPIHeader"."Measure" IS 'Data collected in metric or english units';
COMMENT ON COLUMN dima."tblLPIHeader"."LineLengthAmount" IS 'Length of the line point intercept transect (line)';
COMMENT ON COLUMN dima."tblLPIHeader"."SpacingIntervalAmount" IS 'Length between collection points';
COMMENT ON COLUMN dima."tblLPIHeader"."SpacingType" IS 'Units for length between collection points (cm, m, or ft)';
COMMENT ON COLUMN dima."tblLPIHeader"."HeightOption" IS 'Data collection type for height (no height, every point, or ad hoc)';
COMMENT ON COLUMN dima."tblLPIHeader"."HeightUOM" IS 'Height units (cm or in)';
COMMENT ON COLUMN dima."tblLPIHeader"."ShowCheckbox" IS 'Display checkbox or not';
COMMENT ON COLUMN dima."tblLPIHeader"."CheckboxLabel" IS 'User entered "label" for checkbox (e.g., dead)';
COMMENT ON COLUMN dima."tblLPIHeader"."numCanopy" IS 'Number of top layer foliar hits for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."numBare" IS 'Number of bare ground hits for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."numBasal" IS 'Number of basal cover hits for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctCanopy" IS 'Percent foliar hits (number of top layer foliar hits/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctBare" IS 'Percent bare ground (number of bare ground hits/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctBasal" IS 'Percent basal hits (number of basal hits/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctCheckedPlants" IS 'Percent checked plants (number of plants checked/total number of plant codes)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctCheckedTopPlants" IS 'Percent top layer plants checked (number of checked top layer plants/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctCheckedTopPoints" IS 'Percent top layer positions checked (number of checked top layer positions/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."LayerHeights" IS 'Heights collected for each layer (top, lower layers and soil surface)';
COMMENT ON COLUMN dima."tblLPIHeader"."WoodyHerbHeights" IS 'Heights collected for woody and herbaceous plants';
COMMENT ON COLUMN dima."tblLPIHeader"."pctCheckedSoil" IS 'Percent soil surface positions checked (number of checked soil surface positions/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."avgHeightTop" IS 'Average of the heights entered for the top layer (sum of heights for top layer/total number of top layer heights entered)';
COMMENT ON COLUMN dima."tblLPIHeader"."Notes" IS 'Notes for LPI';
COMMENT ON COLUMN dima."tblLPIHeader"."avgHeightLower1" IS 'Average height of lower canopy 1';
COMMENT ON COLUMN dima."tblLPIHeader"."avgHeightLower2" IS 'Average height of lower canopy 1';
COMMENT ON COLUMN dima."tblLPIHeader"."avgHeightLower3" IS 'Average height of lower canopy 1';
COMMENT ON COLUMN dima."tblLPIHeader"."avgHeightLower4" IS 'Average height of lower canopy 1';
COMMENT ON COLUMN dima."tblLPIHeader"."avgHeightSurface" IS 'Average height of lower canopy 1';
COMMENT ON COLUMN dima."tblLPIHeader"."numGrCovTotal" IS 'Total number of Ground Cover Hits for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."numGrCovBetween" IS 'Number of Ground Cover Hits between plant cover for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."numGrCovUnder" IS 'Number of Ground Cover Hits under plant cover for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."numLitterTotal" IS 'Total number of Litter Hits for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."numLitterBetween" IS 'Total number of Litter Hits between plant cover for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."numLitterUnder" IS 'Total number of Litter Hits under plant cover for the line (transect)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctGrCovTotal" IS 'Percent ground cover total (number of ground cover hits/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctGrCovBetween" IS 'Percent ground cover under "None" (number of ground cover hits under a "None"/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctGrCovUnder" IS 'Percent ground cover under plant cover (number of ground cover hits under a plant code/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctLitterTotal" IS 'Percent total litter (number of position where litter occurs/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctLitterBetween" IS 'Percent litter under "None" (number of litter hits under a "None"/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."pctLitterUnder" IS 'Percent litter under plant cover (number of litter hits under a plant code/total number of positions completed)';
COMMENT ON COLUMN dima."tblLPIHeader"."HeightNoneOption" IS 'Permit non-zero height in Top Canopy when "None"';
COMMENT ON COLUMN dima."tblLPIHeader"."avgHeightWoody" IS 'Average height of woody species';
COMMENT ON COLUMN dima."tblLPIHeader"."avgHeightHerb" IS 'Average height of herbacious species';

-- tblLPIDetail
COMMENT ON TABLE dima."tblLPIDetail" IS 'Contains data for the Line-point Intercept method.';
COMMENT ON COLUMN dima."tblLPIDetail"."RecKey" IS 'Unique record key for line-point intercept';
COMMENT ON COLUMN dima."tblLPIDetail"."PointLoc" IS 'Point location on tape (e.g., 0.5 m)';
COMMENT ON COLUMN dima."tblLPIDetail"."PointNbr" IS 'Point number (1,2, 3....X)';
COMMENT ON COLUMN dima."tblLPIDetail"."TopCanopy" IS 'Species code or None in top canopy';
COMMENT ON COLUMN dima."tblLPIDetail"."Lower1" IS 'Species or litter code in lower 1 canopy';
COMMENT ON COLUMN dima."tblLPIDetail"."Lower2" IS 'Species or litter code in lower 2 canopy';
COMMENT ON COLUMN dima."tblLPIDetail"."Lower3" IS 'Species or litter code in lower 2 canopy';
COMMENT ON COLUMN dima."tblLPIDetail"."Lower4" IS 'Species or litter code in lower 3 canopy';
COMMENT ON COLUMN dima."tblLPIDetail"."SoilSurface" IS 'Plant code or soil surface code';
COMMENT ON COLUMN dima."tblLPIDetail"."HeightTop" IS 'Height of top species';
COMMENT ON COLUMN dima."tblLPIDetail"."ChkboxTop" IS 'User defined checkbox (checked=true, unchecked = false) for top canopy';
COMMENT ON COLUMN dima."tblLPIDetail"."ChkboxLower1" IS 'User defined checkbox (checked=true, unchecked = false) for lower canopy 1';
COMMENT ON COLUMN dima."tblLPIDetail"."ChkboxLower2" IS 'User defined checkbox (checked=true, unchecked = false) for lower canopy 2';
COMMENT ON COLUMN dima."tblLPIDetail"."ChkboxLower3" IS 'User defined checkbox (checked=true, unchecked = false) for lower canopy 3';
COMMENT ON COLUMN dima."tblLPIDetail"."ChkboxLower4" IS 'User defined checkbox (checked=true, unchecked = false) for lower canopy 4';
COMMENT ON COLUMN dima."tblLPIDetail"."ChkboxSoil" IS 'User defined checkbox (checked=true, unchecked = false) for soil surface';
COMMENT ON COLUMN dima."tblLPIDetail"."HeightLower1" IS 'Height of lower 1 species';
COMMENT ON COLUMN dima."tblLPIDetail"."HeightLower2" IS 'Height of lower 2 species';
COMMENT ON COLUMN dima."tblLPIDetail"."HeightLower3" IS 'Height of lower 3 species';
COMMENT ON COLUMN dima."tblLPIDetail"."HeightLower4" IS 'Height of lower 4 species';
COMMENT ON COLUMN dima."tblLPIDetail"."HeightSurface" IS 'Height of surface';
COMMENT ON COLUMN dima."tblLPIDetail"."HeightWoody" IS 'Height of woody species';
COMMENT ON COLUMN dima."tblLPIDetail"."HeightHerbaceous" IS 'Height of herbaceous species';
COMMENT ON COLUMN dima."tblLPIDetail"."ShrubShape" IS 'Shrub shape (columnar, mixed, spreading)';

-- tblSoilStabHeader
COMMENT ON TABLE dima."tblSoilStabHeader" IS 'Contains method metadata and summary data for the Soil Stability Test method (Monitoring Manual v1 2nd ed., Core Methods, p. 47).';
COMMENT ON COLUMN dima."tblSoilStabHeader"."PlotKey" IS 'Unique key for plot';
COMMENT ON COLUMN dima."tblSoilStabHeader"."RecKey" IS 'Unique key for soil stability record';
COMMENT ON COLUMN dima."tblSoilStabHeader"."DateModified" IS 'Date record was created or last modified';
COMMENT ON COLUMN dima."tblSoilStabHeader"."FormType" IS 'Form for soil stability';
COMMENT ON COLUMN dima."tblSoilStabHeader"."FormDate" IS 'Date data was collected (defaults to today''s date although user can modify)';
COMMENT ON COLUMN dima."tblSoilStabHeader"."LineKey" IS 'Unique key for line (transect)';
COMMENT ON COLUMN dima."tblSoilStabHeader"."Observer" IS 'Person taking the actual measurements';
COMMENT ON COLUMN dima."tblSoilStabHeader"."Recorder" IS 'Person doing the recording of measurements in the database or on paper forms';
COMMENT ON COLUMN dima."tblSoilStabHeader"."DataEntry" IS 'Person doing transcription of data into the database if it was recorded on paper';
COMMENT ON COLUMN dima."tblSoilStabHeader"."DataErrorChecking" IS 'Person doing error checking of data';
COMMENT ON COLUMN dima."tblSoilStabHeader"."SoilStabSubSurface" IS 'Surface only or surface and subsurface samples';
COMMENT ON COLUMN dima."tblSoilStabHeader"."SoilStabTimeInterval" IS 'Time interval between samples: 15 or 30 seconds';
COMMENT ON COLUMN dima."tblSoilStabHeader"."SoilStabDataEntryLayout" IS 'Vertical or horizontal data entry (currently locked)';
COMMENT ON COLUMN dima."tblSoilStabHeader"."AllAvgSurf" IS 'Average stability of all surface samples';
COMMENT ON COLUMN dima."tblSoilStabHeader"."AllAvgSub" IS 'Average stability of all sub-surface samples';
COMMENT ON COLUMN dima."tblSoilStabHeader"."ProAvgSurf" IS 'Average stability of all protected surface samples';
COMMENT ON COLUMN dima."tblSoilStabHeader"."ProAvgSub" IS 'Average stability of all protected sub-surface samples';
COMMENT ON COLUMN dima."tblSoilStabHeader"."NCAvgSurf" IS 'Average stability of all unprotected surface samples';
COMMENT ON COLUMN dima."tblSoilStabHeader"."NCAvgSub" IS 'Average stability of all unprotected sub-surface samples';
COMMENT ON COLUMN dima."tblSoilStabHeader"."NoVegAvgSurf" IS 'Average stability of all surface samples where "Veg" is left blank';
COMMENT ON COLUMN dima."tblSoilStabHeader"."NoVegAvgSub" IS 'Average stability of all sub-surface samples where "Veg" is left blank';
COMMENT ON COLUMN dima."tblSoilStabHeader"."PctSurf6" IS 'Percent of surface samples that equal "6"';
COMMENT ON COLUMN dima."tblSoilStabHeader"."PctSub6" IS 'Percent of surface samples that equal "6"';
COMMENT ON COLUMN dima."tblSoilStabHeader"."Notes" IS 'User notes';

-- tblSoilStabDetail
COMMENT ON TABLE dima."tblSoilStabDetail" IS 'Contains data for the Soil Stability Test method.';
COMMENT ON COLUMN dima."tblSoilStabDetail"."RecKey" IS 'Unique record key for soil stability';
COMMENT ON COLUMN dima."tblSoilStabDetail"."BoxNum" IS 'Box number identifying soil stability box';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Line1" IS 'Line number where samples were collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Line2" IS 'Line number where samples were collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Line3" IS 'Line number where samples were collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Line4" IS 'Line number where samples were collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Line5" IS 'Line number where samples were collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Line6" IS 'Line number where samples were collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos1" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos2" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos3" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos4" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos5" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos6" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos7" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos8" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos9" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos10" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos11" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos12" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos13" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos14" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos15" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos16" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos17" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Pos18" IS 'Position on line (transect) were sample was collected';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg1" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg2" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg3" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg4" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg5" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg6" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg7" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg8" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg9" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg10" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg11" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg12" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg13" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg14" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg15" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg16" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg17" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Veg18" IS 'Vegetation where sample was collected (NC no cover; G perennial grass and grass/shrub mix; F perennial forb; Sh shrub canopy; or T tree canopy)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating1" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating2" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating3" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating4" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating5" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating6" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating7" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating8" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating9" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating10" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating11" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating12" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating13" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating14" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating15" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating16" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating17" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Rating18" IS 'Stability value (1  50% of structural integrity lost (melts) within 5 seconds of immersion in water, AND <10% remains after 5 dipping cycles , OR soil too unstable to sample (falls through sieve); 2  50% of structural integrity lost (melts) 5-30 seconds after immersion AND <10% remains after 5 dipping cycles; 3  50% of structural integrity lost (melts) 30-300 seconds after immersion, OR < 10% of soil remains on the sieve after five dipping cycles; 4  10–25% of soil remains on the sieve after five dipping cycles; 5  25–75% of soil remains on the sieve after five dipping cycles; or 6  75–100% of soil remains on the sieve after five dipping cycles.)';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro1" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro2" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro3" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro4" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro5" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro6" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro7" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro8" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro9" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro10" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro11" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro12" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro13" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro14" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro15" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro16" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro17" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Hydro18" IS 'Indicates sample is hydrophobic when checked';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In1" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In2" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In3" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In4" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In5" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In6" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In7" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In8" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In9" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In10" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In11" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In12" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In13" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In14" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In15" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In16" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In17" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."In18" IS 'Time to place sample in water';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip1" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip2" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip3" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip4" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip5" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip6" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip7" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip8" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip9" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip10" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip11" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip12" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip13" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip14" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip15" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip16" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip17" IS 'Time to dip sample';
COMMENT ON COLUMN dima."tblSoilStabDetail"."Dip18" IS 'Time to dip sample';
